export const ActionTypes = {
    STUDENT_PAID: 'STUDENT_PAID',
    COMPLAINTS: 'COMPLAINTS',
    SAVE_HOSTEL: 'SAVE_HOSTEL',
    ADD_COURSE: 'ADD_COURSE',
    ADD_RESULT: 'ADD_RESULT',
    REGISTER_COURSES: 'REGISTER_COURSES',
    REGISTER_RESULTS: 'REGISTER_RESULTS',
    APPROVE_COURSES: 'APPROVE_COURSES',
    LOGOUT: 'LOGOUT'
}