export const ActionTypes = {
    STUDENT_PAID: 'STUDENT_PAID',
    COMPLAINTS: 'COMPLAINTS',
    SAVE_HOSTEL: 'SAVE_HOSTEL',
    ADD_COURSE: 'ADD_COURSE',
    REGISTER_COURSES : 'REGISTER_COURSES',
    LOGOUT: 'LOGOUT'
}